language: python
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- mkdocs build --verbose --clean --strict
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GH_TOKEN
 local_dir: site
 on:
   branch: master

notifications:
  irc:
    channels:
      - "chat.freenode.net#jacobson"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author})"
      - "Commit message : %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
