language: python
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- python -m compileall
- mkdocs build --verbose --clean --strict
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GH_TOKEN
 local_dir: site
 on:
   branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4278e87ba84ccb7de4d8
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
