site_name: Test-Doks
site_description: Testing MkDocs
site_url: https://kurtjacobson.github.io/Test-Repo/

repo_url: https://github.com/KurtJacobson/Test-Repo
repo_name: GitHub

theme: readthedocs

pages:
- Home: index.md
- Installation:
  - Installing: installation.md

