site_name: Test-Repo
site_description: For testing MkDocs
site_url: https://kurtjacobson.github.io/Test-Repo/
site_dir: site

repo_name: KurtJacobson/Test-Repo
repo_url: https://github.com/KurtJacobson/Test-Repo/

theme: material

pages:
- Home: index.md
- Installation:
  - Installing: installation.md
- Modules:
  - Status Monitor: status_monitor.md
- Documentation:
  - Building Docs: building_docs.md

markdown_extensions:
  - admonition
  - codehilite(linenums=true)

extra:
  palette:
    primary: Gray
    accent: Indigo
